docs: add documentation for workspaces + general cleanup (#402)
Summary:
This makes some of the changes listed in https://docs.google.com/document/d/14icG0GJG1nPHF3DW7yMreZpe3S8FwYdrI_XYIzDTSbI/edit#heading=h.6ixj5co4aocb

* Adds workspaces documention
* Adds coverage test to docs build to ensure all exported methods/classes are documented in the docs.
* Adds previously undocumented methods/classes to docs
* Moves torchconfig from experimental to beta
* Splits docker/local scheduler docs
* Reshuffles the sidebar to prioritize the schedulers over some of the other content

Next steps:

* update readme/index/quickstart guides to highlight workspaces + patching w/ ddp builtin
* deprioritize/remove some of the more complex custom component examples

Pull Request resolved: https://github.com/pytorch/torchx/pull/402

Test Plan:
```
$ make -C docs coverage; and cat docs/build/0.1.2dev0/coverage/python.txt
$ pyre
$ pytest
```
CI
![Screenshot 2022-02-28 at 17-21-17 torchx workspace — PyTorch TorchX main documentation](https://user-images.githubusercontent.com/909104/156086755-8330fece-dc86-442d-a656-aaef775bd3e5.png)

Reviewed By: kiukchung

Differential Revision: D34540003

Pulled By: d4l3k

fbshipit-source-id: 271b084d36bdf256547cae755fbeb0e603abac66

diff --git a/.github/workflows/doc-build.yaml b/.github/workflows/doc-build.yaml
--- a/.github/workflows/doc-build.yaml
+++ b/.github/workflows/doc-build.yaml
@@ -42,6 +42,17 @@ jobs:
         run: |
           cd docs
           make papermill
+      - name: Coverage
+        run: |
+          set -ex
+          cd docs
+          make coverage
+          if [ "$(wc -l build/*/coverage/python.txt)" -ne 2 ]
+          then
+              cat build/*/coverage/python.txt
+              echo "missing documentation coverage!"
+              exit 1
+          fi
 
   docpush:
     runs-on: ubuntu-18.04
